{
 "title": "FlowerPower🌻",
 "time": { "from": "2020-12-27T22:36:12.053Z", "to": "2020-12-28T00:50:45.143Z" },
 "panels": [
  {
   "title": "MiFlora Moisture",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"moisture\"}"
    }
   ]
  },
  {
   "title": "MiFlora Sunlight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"light\"}"
    }
   ]
  },
  {
   "title": "MiFlora Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"temperature\"}"
    },
    {}
   ]
  },
  {
   "title": "MiFlora Fertility",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Soil Fertility" }
   ],
   "targets": [
    {
     "expr": "miflora_primary{resource_type=\"conductivity\"}"
    }
   ]
  }
 ]
}