global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - moisture.rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  # Living Room Scrapes
  - job_name: baldy_ficus 
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6000']
        labels: 
          instance: living_room
  - job_name: rubber_tree
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6001']
        labels: 
          instance: living_room
  - job_name: japanese_bamboo
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6002']
        labels: 
          instance: living_room
  - job_name: sideshow_bob
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6003']
        labels: 
          instance: living_room

  # Bedroom 
  - job_name: pink_rubber
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6010']
        labels: 
          instance: bedroom
  - job_name: cheese_plant
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6011']
        labels: 
          instance: bedroom
  - job_name: money_tree
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6012']
        labels: 
          instance: bedroom

  # Babyroom 
  - job_name: aralia_fabian
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.34:6020']
        labels: 
          instance: babyroom
  - job_name: small_rubber_tree
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.34:6021']
        labels: 
          instance: babyroom
  # - job_name: aralia_fabian
  #   metrics_path: '/'
  #   static_configs:
  #     - targets: ['192.168.86.34:6022']
  #       labels: 
  #         instance: babyroom

  # Spare room
  - job_name: spider_plant
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.39:6030']
        labels: 
          instance: spareroom
  - job_name: begonia
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.39:6031']
        labels: 
          instance: spareroom

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alerts-prometheuz:9093"
