global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - example.rules

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: baldy_ficus 
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6000']
        labels: 
          instance: living_room
  - job_name: rubber_tree
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6001']
        labels: 
          instance: living_room
  - job_name: japanese_bamboo
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6002']
        labels: 
          instance: living_room
  - job_name: pink_rubber
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6010']
        labels: 
          instance: bedroom
  - job_name: cheese_plant
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6011']
        labels: 
          instance: bedroom
  - job_name: money_tree
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6012']
        labels: 
          instance: bedroom

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alerts-prometheuz:9093"
