global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: miflora
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6000']
  - job_name: rubberplant
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6001']
  - job_name: rubberplant2
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6002']
