global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: a
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6000']
  - job_name: b
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6001']
  - job_name: c
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.30:6002']
  - job_name: d
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6010']
  - job_name: e
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6011']
  - job_name: f
    metrics_path: '/'
    static_configs:
      - targets: ['192.168.86.29:6012']